# Generated by Django 4.2.13 on 2024-06-25 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('ioc', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'tennis_country',
            },
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('hand', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('hand_description', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'tennis_hand',
            },
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('match_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('match_num', models.IntegerField(null=True)),
                ('score', models.CharField(max_length=50, null=True)),
                ('best_of', models.CharField(max_length=5, null=True)),
                ('round', models.CharField(max_length=10, null=True)),
                ('minutes', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'tennis_matches',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tourney_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tourney_name', models.CharField(max_length=100)),
                ('surface', models.CharField(max_length=20, null=True)),
                ('draw_size', models.IntegerField(null=True)),
                ('tourney_level', models.CharField(max_length=10, null=True)),
                ('tourney_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'tennis_tournament',
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=100)),
                ('height', models.IntegerField(null=True)),
                ('hand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tennis.hand')),
                ('ioc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tennis.country')),
            ],
            options={
                'db_table': 'tennis_players',
            },
        ),
        migrations.CreateModel(
            name='PlayerMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_role', models.CharField(max_length=10, null=True)),
                ('seed', models.IntegerField(null=True)),
                ('entry', models.CharField(max_length=10, null=True)),
                ('ranking', models.IntegerField(null=True)),
                ('ranking_points', models.IntegerField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tennis.matches')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tennis.players')),
            ],
            options={
                'db_table': 'tennis_playermatch',
            },
        ),
        migrations.CreateModel(
            name='MatchStats',
            fields=[
                ('match_stats_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ace', models.IntegerField(null=True)),
                ('df', models.IntegerField(null=True)),
                ('svpt', models.IntegerField(null=True)),
                ('firstIn', models.IntegerField(null=True)),
                ('firstWon', models.IntegerField(null=True)),
                ('secondWon', models.IntegerField(null=True)),
                ('SvGms', models.IntegerField(null=True)),
                ('bpSaved', models.IntegerField(null=True)),
                ('bpFaced', models.IntegerField(null=True)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tennis.matches')),
            ],
            options={
                'db_table': 'tennis_matchstats',
            },
        ),
        migrations.AddField(
            model_name='matches',
            name='tourney_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tennis.tournament'),
        ),
    ]
